import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const DAY=86400000;
const clean=(v:unknown)=>String(v??"").trim();
const iso=(d:Date)=>d.toISOString().slice(0,10);
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const days=(a:string,b:string)=>Math.abs(Math.round((new Date(`${a}T12:00:00Z`).getTime()-new Date(`${b}T12:00:00Z`).getTime())/DAY));
const merchant=(s:string)=>s.toLowerCase().replace(/\b(?:visa|debit|purchase|payment|online|transfer|etransfer|e-transfer|withdrawal|deposit)\b/g," ").replace(/\d+/g," ").replace(/[^a-z]+/g," ").replace(/\s+/g," ").trim().slice(0,80)||"unknown";
function key(){const k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(k)return k;const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(!raw)return"";try{const p=JSON.parse(raw);return p.default||Object.values(p)[0]||"";}catch{return"";}}
function payload(v:any){if(!v)return{};if(typeof v==="string"){try{return JSON.parse(v)||{};}catch{return{};}}return v;}
const R:any={none:0,view:1,edit:2,admin:3};
function level(p:any){if(clean(p?.email).toLowerCase()==="rickothebarber@gmail.com"||clean(p?.role).toLowerCase()==="owner")return"admin";if(!p||p.active===false)return"none";const x=payload(p.permissions);return clean(x?.modules?.finance||x?.finance||"none").toLowerCase();}
function allowed(p:any,id:string){if(!id||id==="all-businesses")return false;if(clean(p?.email).toLowerCase()==="rickothebarber@gmail.com"||clean(p?.role).toLowerCase()==="owner")return true;const x=payload(p.permissions),ids=Array.isArray(x.business_unit_ids)?x.business_unit_ids.map(String):[];return clean(x.business_scope).toLowerCase()==="all"||ids.includes("all-businesses")||ids.includes(id)||clean(p.business_unit_id)===id;}
function cadence(n:number):[string,number]{if(n<=10)return["weekly",7];if(n<=20)return["biweekly",14];if(n<=45)return["monthly",30];if(n<=120)return["quarterly",91];if(n<=420)return["yearly",365];return["irregular",Math.max(1,Math.round(n))];}
function dates(start:string,step:number,end:string){const out:string[]=[];let d=new Date(`${start}T12:00:00Z`),e=new Date(`${end}T12:00:00Z`);while(d<=e){out.push(iso(d));d=new Date(d.getTime()+step*DAY);}return out;}
async function snapshot(admin:any,businessId:string){const today=iso(new Date());const [a,b,c,d]=await Promise.all([
 admin.from("finance_reconciliations").select("*").eq("business_unit_id",businessId).order("confidence",{ascending:false}).limit(50),
 admin.from("finance_recurring_patterns").select("*").eq("business_unit_id",businessId).eq("active",true).order("next_expected_date"),
 admin.from("finance_calendar_events").select("*").eq("business_unit_id",businessId).gte("event_date",today).order("event_date").limit(150),
 admin.from("finance_forecast_snapshots").select("*").eq("business_unit_id",businessId).order("horizon_days")
]);for(const r of[a,b,c,d])if(r.error)throw r.error;return{reconciliations:a.data||[],recurring_patterns:b.data||[],calendar:c.data||[],forecasts:d.data||[],refreshed_at:new Date().toISOString()};}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{
 const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return json({error:"Supabase secrets missing"},500);const admin=createClient(url,secret,{auth:{persistSession:false}});const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");const {data:auth,error:ae}=await admin.auth.getUser(token);if(ae||!auth.user)return json({error:"Invalid session"},401);const {data:profile,error:pe}=await admin.from("user_profiles").select("email,role,active,business_unit_id,permissions").eq("id",auth.user.id).maybeSingle();if(pe||!profile)return json({error:"Profile unavailable"},403);
 const body=await req.json().catch(()=>({}));const action=clean(body.action||"snapshot").toLowerCase(),businessId=clean(body.businessId||body.business_id);if(R[level(profile)]<1||!allowed(profile,businessId))return json({error:"Finance access denied"},403);
 if(action==="snapshot")return json(await snapshot(admin,businessId));
 if(action==="confirm_match"||action==="reject_match"){if(R[level(profile)]<2)return json({error:"Finance edit access required"},403);const id=clean(body.id),status=action==="confirm_match"?"confirmed":"rejected";const {data:r,error}=await admin.from("finance_reconciliations").update({status,reviewed_at:new Date().toISOString(),reviewed_by:auth.user.id,updated_at:new Date().toISOString()}).eq("id",id).eq("business_unit_id",businessId).select("*").single();if(error)throw error;if(status==="confirmed")await admin.from("finance_reconciliations").update({status:"rejected",updated_at:new Date().toISOString()}).eq("bank_transaction_id",r.bank_transaction_id).neq("id",id).eq("status","suggested");return json({reconciliation:r});}
 if(R[level(profile)]<2)return json({error:"Finance edit access required"},403);
 const cutoff=iso(new Date(Date.now()-370*DAY));const [bankR,runsR,obsR,squareR]=await Promise.all([
  admin.from("finance_transactions").select("*").eq("business_unit_id",businessId).eq("source","csv").gte("transaction_date",cutoff).order("transaction_date"),
  admin.from("payroll_runs").select("*").eq("business_unit_id",businessId).eq("status","locked").order("week_end",{ascending:false}).limit(30),
  admin.from("finance_obligations").select("*").eq("business_unit_id",businessId).eq("status","active"),
  admin.from("finance_transactions").select("id,transaction_date,amount").eq("business_unit_id",businessId).eq("source","square").gte("transaction_date",cutoff)
 ]);for(const r of[bankR,runsR,obsR,squareR])if(r.error)throw r.error;const bank=bankR.data||[],runs=runsR.data||[],obs=obsR.data||[],square=squareR.data||[],runIds=runs.map((x:any)=>x.id);let entries:any[]=[];if(runIds.length){const e=await admin.from("payroll_entries").select("id,payroll_run_id,staff_id,staff_name_snapshot,take_home").in("payroll_run_id",runIds);if(e.error)throw e.error;entries=e.data||[];}const runMap=new Map(runs.map((x:any)=>[x.id,x]));

 if(["full_refresh","scan_reconciliation"].includes(action)){
  await admin.from("finance_reconciliations").delete().eq("business_unit_id",businessId).eq("status","suggested");const all:any[]=[];
  const squareByDate=new Map<string,{total:number,id:string}>();for(const s of square){const g=squareByDate.get(s.transaction_date)||{total:0,id:s.id};g.total+=Number(s.amount||0);squareByDate.set(s.transaction_date,g);}
  for(const tx of bank){const amt=Number(tx.amount||0),desc=clean(tx.description).toLowerCase();if(!amt)continue;if(tx.direction==="expense"){
   for(const e of entries){const run:any=runMap.get(e.payroll_run_id);if(!run)continue;const ex=Number(e.take_home||0),dd=days(tx.transaction_date,run.week_end||run.week_start),diff=Math.abs(amt-ex);if(dd>14||diff>Math.max(2,ex*.012))continue;let score=65+Math.max(0,20-dd*1.5)+Math.max(0,10-(diff/Math.max(ex,1))*500);const name=clean(e.staff_name_snapshot).toLowerCase();if(name&&name.split(/\s+/).some((p:string)=>p.length>2&&desc.includes(p)))score+=10;all.push({business_unit_id:businessId,bank_transaction_id:tx.id,match_type:"payroll_entry",matched_id:e.id,match_label:`Payroll · ${e.staff_name_snapshot}`,expected_amount:ex,actual_amount:amt,confidence:Math.min(100,Math.round(score)),reason:{date_difference_days:dd,amount_difference:diff,payroll_run_id:e.payroll_run_id}});}
   for(const run of runs){const ex=Number(run.total_staff_payout||0),dd=days(tx.transaction_date,run.week_end||run.week_start),diff=Math.abs(amt-ex);if(dd<=10&&diff<=Math.max(3,ex*.01))all.push({business_unit_id:businessId,bank_transaction_id:tx.id,match_type:"payroll_run",matched_id:run.id,match_label:`Payroll run · ${run.week_label}`,expected_amount:ex,actual_amount:amt,confidence:Math.min(98,Math.round(70+Math.max(0,20-dd*2)+Math.max(0,8-(diff/Math.max(ex,1))*400))),reason:{date_difference_days:dd,amount_difference:diff}});}
   for(const ob of obs){const ex=Number(ob.amount||0),diff=Math.abs(amt-ex),dd=Math.abs(new Date(`${tx.transaction_date}T12:00:00Z`).getUTCDate()-Number(ob.due_day||1));if(diff<=Math.max(3,ex*.03)&&dd<=7){let score=60+Math.max(0,20-dd*2)+Math.max(0,10-(diff/Math.max(ex,1))*200);const first=clean(ob.name).toLowerCase().split(/\s+/)[0];if(first&&desc.includes(first))score+=10;all.push({business_unit_id:businessId,bank_transaction_id:tx.id,match_type:"obligation",matched_id:ob.id,match_label:`Recurring · ${ob.name}`,expected_amount:ex,actual_amount:amt,confidence:Math.min(95,Math.round(score)),reason:{due_day_difference:dd,amount_difference:diff}});}}
  }else if(tx.direction==="income"){for(const[d,g]of squareByDate){const dd=days(tx.transaction_date,d),diff=Math.abs(amt-g.total);if(dd<=4&&diff<=Math.max(5,g.total*.12))all.push({business_unit_id:businessId,bank_transaction_id:tx.id,match_type:"square_deposit",matched_id:g.id,match_label:`Square sales · ${d}`,expected_amount:g.total,actual_amount:amt,confidence:Math.min(95,Math.round(55+Math.max(0,20-dd*4)+Math.max(0,20-(diff/Math.max(g.total,1))*150))),reason:{sale_date:d,date_difference_days:dd,amount_difference:diff}});}}
  }
  const grouped=new Map<string,any[]>();for(const c of all){const a=grouped.get(c.bank_transaction_id)||[];a.push(c);grouped.set(c.bank_transaction_id,a);}const rows=[...grouped.values()].flatMap(a=>a.sort((x,y)=>y.confidence-x.confidence).slice(0,3)).filter(x=>x.confidence>=60);if(rows.length){const u=await admin.from("finance_reconciliations").upsert(rows,{onConflict:"bank_transaction_id,match_type,matched_id"});if(u.error)throw u.error;}
 }

 if(["full_refresh","refresh_patterns","refresh_calendar"].includes(action)){
  const groups=new Map<string,any[]>();for(const tx of bank.filter((x:any)=>x.direction==="expense")){const k=`${tx.direction}:${merchant(tx.description)}`,a=groups.get(k)||[];a.push(tx);groups.set(k,a);}for(const[k,a]of groups){if(a.length<2)continue;a.sort((x,y)=>String(x.transaction_date).localeCompare(String(y.transaction_date)));const ints=a.slice(1).map((x:any,i:number)=>days(x.transaction_date,a[i].transaction_date)),avgI=ints.reduce((s,n)=>s+n,0)/ints.length,[cad,step]=cadence(avgI);if(cad==="irregular")continue;const amounts=a.map((x:any)=>Number(x.amount||0)),avg=amounts.reduce((s,n)=>s+n,0)/amounts.length,variance=Math.sqrt(amounts.reduce((s,n)=>s+(n-avg)**2,0)/amounts.length),stability=Math.max(0,1-variance/Math.max(avg,1)),intervalDev=ints.reduce((s,n)=>s+Math.abs(n-avgI),0)/ints.length,confidence=Math.max(55,Math.min(95,Math.round(45+Math.min(25,a.length*5)+stability*15+Math.max(0,10-intervalDev)))),last=a[a.length-1].transaction_date,next=iso(new Date(new Date(`${last}T12:00:00Z`).getTime()+step*DAY));const merchantKey=k.split(":").slice(1).join(":");const u=await admin.from("finance_recurring_patterns").upsert({business_unit_id:businessId,merchant_key:merchantKey,label:clean(a[a.length-1].description),direction:a[0].direction,avg_amount:Number(avg.toFixed(2)),amount_variance:Number(variance.toFixed(2)),cadence:cad,interval_days:step,occurrence_count:a.length,last_seen_date:last,next_expected_date:next,confidence,active:true,updated_at:new Date().toISOString()},{onConflict:"business_unit_id,merchant_key,direction"});if(u.error)throw u.error;}
  const pr=await admin.from("finance_recurring_patterns").select("*").eq("business_unit_id",businessId).eq("active",true);if(pr.error)throw pr.error;const patterns=pr.data||[];await admin.from("finance_calendar_events").delete().eq("business_unit_id",businessId).in("status",["predicted","scheduled"]);const today=new Date(),end=new Date(Date.now()+90*DAY),events:any[]=[];
  for(const ob of obs){for(let m=0;m<4;m++){const d=new Date(Date.UTC(today.getUTCFullYear(),today.getUTCMonth()+m,Math.min(Number(ob.due_day||1),28),12));if(d<new Date(`${iso(today)}T00:00:00Z`)||d>end)continue;events.push({business_unit_id:businessId,event_date:iso(d),event_type:"obligation",label:ob.name,direction:"expense",expected_amount:Number(ob.amount||0),status:"scheduled",confidence:100,source_type:"obligation",source_id:ob.id,metadata:{frequency:ob.frequency,category:ob.category}});}}
  for(const p of patterns){if(!p.next_expected_date||p.direction!=="expense")continue;for(const d of dates(p.next_expected_date,Number(p.interval_days||30),iso(end)))events.push({business_unit_id:businessId,event_date:d,event_type:"recurring_expense",label:p.label,direction:"expense",expected_amount:Number(p.avg_amount||0),status:"predicted",confidence:p.confidence,source_type:"recurring_pattern",source_id:p.id,metadata:{cadence:p.cadence,occurrences:p.occurrence_count,variance:p.amount_variance}});}
  const recent=runs.slice(0,6);if(recent.length){const avg=recent.reduce((s:any,r:any)=>s+Number(r.total_staff_payout||0),0)/recent.length,latest=recent[0];let d=new Date(`${latest.week_end||latest.week_start}T12:00:00Z`);for(let i=0;i<13;i++){d=new Date(d.getTime()+7*DAY);if(d>end)break;events.push({business_unit_id:businessId,event_date:iso(d),event_type:"payroll",label:"Expected staff payroll",direction:"expense",expected_amount:Number(avg.toFixed(2)),status:"predicted",confidence:Math.min(90,60+recent.length*5),source_type:"payroll_prediction",source_id:latest.id,metadata:{based_on_runs:recent.length}});}}
  const salesCut=iso(new Date(Date.now()-28*DAY)),recentSquare=square.filter((s:any)=>s.transaction_date>=salesCut),weeklySales=recentSquare.reduce((s:number,x:any)=>s+Number(x.amount||0),0)/4;if(weeklySales>0){const source=recentSquare[0]?.id;for(let d=new Date(Date.now()+7*DAY);d<=end;d=new Date(d.getTime()+7*DAY))events.push({business_unit_id:businessId,event_date:iso(d),event_type:"sales",label:"Expected weekly Square sales",direction:"income",expected_amount:Number(weeklySales.toFixed(2)),status:"predicted",confidence:65,source_type:"sales_prediction",source_id:source,metadata:{basis:"last_28_days_square_sales"}});}
  if(events.length){const u=await admin.from("finance_calendar_events").upsert(events,{onConflict:"business_unit_id,source_type,source_id,event_date"});if(u.error)throw u.error;}
  await admin.from("finance_forecast_snapshots").delete().eq("business_unit_id",businessId);const cr=await admin.from("finance_calendar_events").select("*").eq("business_unit_id",businessId).gte("event_date",iso(today)).lte("event_date",iso(end));if(cr.error)throw cr.error;const cal=cr.data||[];
  for(const h of[7,30,60,90]){const until=iso(new Date(Date.now()+h*DAY)),sub=cal.filter((e:any)=>e.event_date<=until&&e.status!=="cancelled"),ein=sub.filter((e:any)=>e.direction==="income").reduce((s:number,e:any)=>s+Number(e.expected_amount||0),0),eout=sub.filter((e:any)=>e.direction==="expense").reduce((s:number,e:any)=>s+Number(e.expected_amount||0),0),cin=sub.filter((e:any)=>e.direction==="income"&&e.status==="confirmed").reduce((s:number,e:any)=>s+Number(e.expected_amount||0),0),cout=sub.filter((e:any)=>e.direction==="expense"&&e.status==="confirmed").reduce((s:number,e:any)=>s+Number(e.expected_amount||0),0),net=ein-eout,risk=net<0?(Math.abs(net)>Math.max(ein,1)*.5?"high":"watch"):"normal";const ins=await admin.from("finance_forecast_snapshots").insert({business_unit_id:businessId,horizon_days:h,expected_in:ein,expected_out:eout,expected_net:net,confirmed_in:cin,confirmed_out:cout,risk_level:risk,details:{events:sub.length}});if(ins.error)throw ins.error;if(risk!=="normal"){const title=`${h}-day cash-flow forecast needs attention`,since=new Date(Date.now()-DAY).toISOString();const old=await admin.from("owner_activity_events").select("id").eq("business_unit_id",businessId).eq("action","forecast_risk").eq("title",title).gte("created_at",since).limit(1);if(!old.error&&!old.data?.length)await admin.from("owner_activity_events").insert({business_unit_id:businessId,category:"finance",action:"forecast_risk",title,body:`Expected outflow ${eout.toFixed(2)} vs inflow ${ein.toFixed(2)}; projected net ${net.toFixed(2)}.`,source_table:"finance_forecast_snapshots",metadata:{horizon_days:h,expected_in:ein,expected_out:eout,expected_net:net,risk_level:risk}});}}
 }
 return json(await snapshot(admin,businessId));
}catch(err){console.error("finance-intelligence",err);return json({error:err instanceof Error?err.message:"Finance intelligence failed"},500);}});
