import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { SignJWT, importPKCS8 } from "npm:jose@6";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
let cachedJwt="";let cachedJwtExpiresAt=0;
function serviceKey(){const direct=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(direct)return direct;const keys=Deno.env.get("SUPABASE_SECRET_KEYS");if(!keys)return"";try{const parsed=JSON.parse(keys);return parsed.default||Object.values(parsed)[0]||""}catch{return""}}
async function apnsJwt(){const now=Math.floor(Date.now()/1000);if(cachedJwt&&cachedJwtExpiresAt>now+120)return cachedJwt;const keyId=Deno.env.get("APNS_KEY_ID")||"",teamId=Deno.env.get("APNS_TEAM_ID")||"",rawKey=Deno.env.get("APNS_PRIVATE_KEY")||"";if(!keyId||!teamId||!rawKey)throw new Error("APNs credentials are not configured.");const privateKey=await importPKCS8(rawKey.replace(/\\n/g,"\n"),"ES256");cachedJwt=await new SignJWT({}).setProtectedHeader({alg:"ES256",kid:keyId}).setIssuer(teamId).setIssuedAt(now).sign(privateKey);cachedJwtExpiresAt=now+2700;return cachedJwt}
async function sendApns(token:string,title:string,body:string,data:Record<string,unknown>={}){const jwt=await apnsJwt();const bundleId=Deno.env.get("APNS_BUNDLE_ID")||"com.rtbheadquaters.os";const environment=(Deno.env.get("APNS_ENVIRONMENT")||"production").toLowerCase();const host=environment==="sandbox"?"https://api.sandbox.push.apple.com":"https://api.push.apple.com";const response=await fetch(`${host}/3/device/${encodeURIComponent(token)}`,{method:"POST",headers:{authorization:`bearer ${jwt}`,"apns-topic":bundleId,"apns-push-type":"alert","apns-priority":"10","content-type":"application/json"},body:JSON.stringify({aps:{alert:{title,body},sound:"default"},...data})});const details=response.ok?null:await response.json().catch(()=>null);return{ok:response.ok,status:response.status,details}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed."},405);try{const url=Deno.env.get("SUPABASE_URL")||"",key=serviceKey();if(!url||!key)return json({error:"Supabase service configuration is missing."},500);const admin=createClient(url,key,{auth:{persistSession:false}});const {data:jobs,error}=await admin.from("push_notification_queue").select("id,user_id,title,body,data,attempt_count").eq("status","pending").lte("next_attempt_at",new Date().toISOString()).order("created_at",{ascending:true}).limit(50);if(error)throw error;let sent=0,failed=0;for(const job of jobs||[]){const {data:devices,error:deviceError}=await admin.from("push_device_tokens").select("id,token,platform,active").eq("user_id",job.user_id).eq("active",true).eq("platform","ios");if(deviceError){failed++;continue}if(!devices?.length){await admin.from("push_notification_queue").update({status:"no_device",processed_at:new Date().toISOString(),last_error:"No active iOS push token registered for this user."}).eq("id",job.id);continue}let anySuccess=false;const errors:string[]=[];for(const device of devices){try{const result=await sendApns(device.token,job.title,job.body,job.data||{});if(result.ok)anySuccess=true;else{errors.push(`${result.status}:${JSON.stringify(result.details)}`);if([400,410].includes(result.status)){const reason=(result.details as any)?.reason||"";if(["BadDeviceToken","DeviceTokenNotForTopic","Unregistered"].includes(reason))await admin.from("push_device_tokens").update({active:false,disabled_at:new Date().toISOString()}).eq("id",device.id)}}}catch(e){errors.push(e instanceof Error?e.message:String(e))}}const attempts=Number(job.attempt_count||0)+1;if(anySuccess){sent++;await admin.from("push_notification_queue").update({status:"sent",processed_at:new Date().toISOString(),attempt_count:attempts,last_error:errors.length?errors.join(" | ").slice(0,2000):null}).eq("id",job.id)}else{failed++;await admin.from("push_notification_queue").update({status:attempts>=5?"failed":"pending",attempt_count:attempts,last_error:errors.join(" | ").slice(0,2000)||"APNs delivery failed.",next_attempt_at:new Date(Date.now()+Math.min(60,attempts*5)*60000).toISOString(),processed_at:attempts>=5?new Date().toISOString():null}).eq("id",job.id)}}return json({processed:jobs?.length||0,sent,failed})}catch(e){return json({error:e instanceof Error?e.message:"Push dispatch failed."},500)}});
