export const INTEGRATION_PROVIDERS = [
  {
    id: 'google',
    name: 'Google Workspace',
    category: 'Communication',
    authType: 'oauth',
    description: 'Gmail, Calendar, Drive, Contacts and Sheets for owner briefs, scheduling and document workflows.',
    capabilities: ['Gmail', 'Calendar', 'Drive', 'Contacts', 'Sheets'],
    recommended: true,
  },
  {
    id: 'square',
    name: 'Square',
    category: 'Payments & Booking',
    authType: 'oauth',
    description: 'Payments, Appointments, customers, sales, staff activity, loans and cash-drawer signals.',
    capabilities: ['Payments', 'Appointments', 'Customers', 'Sales', 'Loans'],
    recommended: true,
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'Development',
    authType: 'oauth',
    description: 'Repositories, issues, pull requests, Actions failures and deployment engineering signals.',
    capabilities: ['Repositories', 'Issues', 'Pull requests', 'Actions'],
    recommended: true,
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'Communication',
    authType: 'oauth',
    description: 'Team communication, announcements, staff coordination and operational alerts.',
    capabilities: ['Channels', 'Messages', 'Users', 'Alerts'],
    recommended: true,
  },
  {
    id: 'jotform',
    name: 'Jotform',
    category: 'Forms',
    authType: 'api_key',
    description: 'Hiring, ambassador, intake, consent and internal operations forms.',
    capabilities: ['Forms', 'Submissions', 'Documents'],
    recommended: true,
  },
  {
    id: 'canva',
    name: 'Canva',
    category: 'Marketing',
    authType: 'oauth',
    description: 'Brand assets, social content, posters, presentations and reusable templates.',
    capabilities: ['Designs', 'Brand assets', 'Exports'],
    recommended: true,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'AI',
    authType: 'api_key',
    description: 'AI reasoning, classification, drafting, extraction and automation inside Ricko OS.',
    capabilities: ['Responses', 'Agents', 'Embeddings', 'Vision'],
    recommended: true,
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'Development',
    authType: 'oauth',
    description: 'Deployments, domains, environment status, logs and production health.',
    capabilities: ['Deployments', 'Projects', 'Domains', 'Logs'],
  },
  {
    id: 'netlify',
    name: 'Netlify',
    category: 'Development',
    authType: 'oauth',
    description: 'Sites, deploys, forms, functions and production diagnostics.',
    capabilities: ['Sites', 'Deploys', 'Functions'],
  },
  {
    id: 'base44',
    name: 'Base44',
    category: 'Development',
    authType: 'api_key',
    description: 'AI-built RTB applications, resources and sandbox development.',
    capabilities: ['Apps', 'Resources', 'Agents'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Core System',
    authType: 'system',
    description: 'Ricko OS database, authentication, Edge Functions, storage and realtime infrastructure.',
    capabilities: ['Database', 'Auth', 'Functions', 'Storage', 'Realtime'],
    recommended: true,
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    category: 'Infrastructure',
    authType: 'api_key',
    description: 'DNS, tunnels, domain health, security and edge traffic.',
    capabilities: ['DNS', 'Tunnels', 'Security', 'Analytics'],
  },
  {
    id: 'metricool',
    name: 'Metricool',
    category: 'Marketing',
    authType: 'api_key',
    description: 'Social publishing, analytics and marketing performance reporting.',
    capabilities: ['Social analytics', 'Publishing', 'Reports'],
  },
  {
    id: 'booksy',
    name: 'Booksy',
    category: 'Payments & Booking',
    authType: 'manual',
    description: 'RTB Lounge booking source. Track imports and connection health where API access is available.',
    capabilities: ['Bookings', 'Clients', 'Staff schedules'],
  },
  {
    id: 'wave',
    name: 'Wave',
    category: 'Finance',
    authType: 'oauth',
    description: 'Bookkeeping, accounting records, invoices and financial reporting.',
    capabilities: ['Accounting', 'Invoices', 'Transactions'],
  },
  {
    id: 'scotiabank_chase',
    name: 'Scotiabank / Chase',
    category: 'Finance',
    authType: 'manual',
    description: 'POS and banking reconciliation layer when a supported secure data connection is available.',
    capabilities: ['POS', 'Deposits', 'Reconciliation'],
  },
  {
    id: 'google_business',
    name: 'Google Business Profile',
    category: 'Marketing',
    authType: 'oauth',
    description: 'Reviews, profile activity, local visibility and reputation monitoring.',
    capabilities: ['Reviews', 'Locations', 'Performance'],
  },
  {
    id: 'instagram_meta',
    name: 'Instagram / Meta',
    category: 'Marketing',
    authType: 'oauth',
    description: 'Content performance, messages, lead signals and social analytics.',
    capabilities: ['Instagram', 'Insights', 'Messaging'],
  },
  {
    id: 'twilio',
    name: 'Twilio',
    category: 'Communication',
    authType: 'api_key',
    description: 'SMS notifications, reminders and operational messaging.',
    capabilities: ['SMS', 'Messaging', 'Phone'],
  },
  {
    id: 'resend',
    name: 'Resend',
    category: 'Communication',
    authType: 'api_key',
    description: 'Transactional emails generated by Ricko OS.',
    capabilities: ['Transactional email', 'Domains'],
  },
];

export const INTEGRATION_CATEGORIES = ['All', ...new Set(INTEGRATION_PROVIDERS.map((item) => item.category))];

export function getIntegrationProvider(providerId) {
  return INTEGRATION_PROVIDERS.find((item) => item.id === providerId) || null;
}
