import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
function serviceKey() { const direct=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if(direct)return direct; const keys=Deno.env.get("SUPABASE_SECRET_KEYS"); if(!keys)return""; try{const parsed=JSON.parse(keys); return parsed.default||Object.values(parsed)[0]||"";}catch{return"";} }
function permissionPayload(profile:any){let permissions=profile?.permissions||{};if(typeof permissions==="string"){try{permissions=JSON.parse(permissions||"{}");}catch{permissions={};}}return permissions||{};}
function isFinanceAllowed(profile:any){if(!profile)return false;if(String(profile.email||"").toLowerCase()==="rickothebarber@gmail.com"||String(profile.role||"").toLowerCase()==="owner")return true;if(profile.active===false)return false;const p=permissionPayload(profile),level=p?.modules?.finance||p?.finance||"none";return["view","edit","admin"].includes(String(level).toLowerCase());}
function canAccessBusiness(profile:any,businessId:string){if(!profile||!businessId||businessId==="all-businesses")return false;if(String(profile.email||"").toLowerCase()==="rickothebarber@gmail.com"||String(profile.role||"").toLowerCase()==="owner")return true;const p=permissionPayload(profile);if(String(p.business_scope||"").toLowerCase()==="all")return true;const ids=Array.isArray(p.business_unit_ids)?p.business_unit_ids.map(String):[];return ids.includes("all-businesses")||ids.includes(businessId)||String(profile.business_unit_id||"")===businessId;}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed."},405);try{
 const supabaseUrl=Deno.env.get("SUPABASE_URL")||"",key=serviceKey(),geminiKey=Deno.env.get("GEMINI_API_KEY")||"";if(!supabaseUrl||!key)return json({error:"Supabase function secrets are missing."},500);if(!geminiKey)return json({error:"GEMINI_API_KEY is not configured."},500);const admin=createClient(supabaseUrl,key,{auth:{persistSession:false}}),token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");const {data:authData,error:authError}=await admin.auth.getUser(token);if(authError||!authData.user)return json({error:"Your session is invalid or expired."},401);const {data:profile,error:profileError}=await admin.from("user_profiles").select("email,role,permissions,active,business_unit_id").eq("id",authData.user.id).maybeSingle();if(profileError)return json({error:"Could not verify Finance access."},500);if(!isFinanceAllowed(profile))return json({error:"Finance access is not enabled for this account."},403);
 const body=await req.json().catch(()=>({})),businessId=String(body.businessId||body.business_id||"").trim(),question=String(body.question||"Give me a concise financial health check.").trim();if(!canAccessBusiness(profile,businessId))return json({error:"Choose a Finance business you are allowed to access."},403);const monthStart=new Date();monthStart.setDate(1);const monthStartIso=monthStart.toISOString().slice(0,10),today=new Date().toISOString().slice(0,10);
 const [businessR,transactionsR,obligationsR,payrollR,performanceR,reconciliationsR,calendarR,forecastsR,patternsR,evidenceR]=await Promise.all([
  admin.from("business_units").select("id,name,type").eq("id",businessId).maybeSingle(),
  admin.from("finance_transactions").select("transaction_date,direction,amount,category,description,source,external_ref").eq("business_unit_id",businessId).gte("transaction_date",monthStartIso).order("transaction_date",{ascending:false}).limit(160),
  admin.from("finance_obligations").select("name,amount,due_day,frequency,category,status").eq("business_unit_id",businessId).eq("status","active").order("due_day"),
  admin.from("payroll_runs").select("week_label,status,total_net_sales,total_staff_payout,total_deductions,rtb_net,week_start,week_end").eq("business_unit_id",businessId).order("week_start",{ascending:false}).limit(8),
  admin.from("staff_performance_summary").select("total_net_sales,transactions,average_ticket").eq("business_unit_id",businessId).limit(30),
  admin.from("finance_reconciliations").select("match_type,match_label,expected_amount,actual_amount,confidence,status,reason").eq("business_unit_id",businessId).order("confidence",{ascending:false}).limit(60),
  admin.from("finance_calendar_events").select("event_date,event_type,label,direction,expected_amount,status,confidence,source_type").eq("business_unit_id",businessId).gte("event_date",today).order("event_date").limit(80),
  admin.from("finance_forecast_snapshots").select("horizon_days,expected_in,expected_out,expected_net,confirmed_in,confirmed_out,risk_level,generated_at").eq("business_unit_id",businessId).order("generated_at",{ascending:false}).limit(12),
  admin.from("finance_recurring_patterns").select("label,direction,avg_amount,cadence,occurrence_count,next_expected_date,confidence").eq("business_unit_id",businessId).eq("active",true).order("confidence",{ascending:false}).limit(30),
  admin.from("finance_payment_confirmations").select("recipient_name,direction,amount,deposited_at,payment_kind,category_hint,counterparty_type,routing_method,match_status,match_confidence,bank_transaction_id,payroll_entry_id,evidence").eq("business_unit_id",businessId).order("deposited_at",{ascending:false}).limit(80)
 ]);const queryErrors=[businessR,transactionsR,obligationsR,payrollR,performanceR,reconciliationsR,calendarR,forecastsR,patternsR,evidenceR].map((r:any)=>r.error).filter(Boolean);if(queryErrors.length)throw queryErrors[0];const latestForecasts=new Map<number,any>();for(const row of forecastsR.data||[])if(!latestForecasts.has(Number(row.horizon_days)))latestForecasts.set(Number(row.horizon_days),row);
 const payload={business:businessR.data,month_start:monthStartIso,transactions:transactionsR.data||[],recurring_obligations:obligationsR.data||[],detected_recurring_patterns:patternsR.data||[],recent_payroll:payrollR.data||[],performance:performanceR.data||[],payment_evidence:evidenceR.data||[],bank_reconciliation:reconciliationsR.data||[],upcoming_financial_calendar:calendarR.data||[],forecasts:[...latestForecasts.values()].sort((a,b)=>Number(a.horizon_days)-Number(b.horizon_days))};
 const model=Deno.env.get("GEMINI_MODEL")||"gemini-2.0-flash",system=`You are Financial Buddy inside RTB OS, the owner's financial decision-support system. Use only supplied Supabase data. Payment evidence may come from Gmail/Interac, payroll, recurring obligations and imported bank statements. A Gmail confirmation is evidence, not a second transaction. Treat a payment as fully confirmed only when the supplied match status/evidence supports it; otherwise say it is suggested or awaiting bank evidence. Distinguish incoming Interac deposits from outgoing payments. Treat operational revenue, imported bank cash movement, payroll, recurring obligations, reconciliation evidence, calendar events, and forecasts as related but distinct concepts. Never double-count a bank transaction that reconciles an existing payroll, obligation, email confirmation or Square source. Clearly distinguish confirmed values from predicted values and suggested reconciliation matches. Prioritize cash-flow risk, upcoming commitments, unmatched payments, payroll pressure, recurring expenses, unexplained transfers and the next 1-3 owner actions. Never invent bank balances, tax balances, revenue, expenses, or payment status. When evidence is incomplete, name exactly what is missing. Keep answers concise, numerical and practical.`;
 const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":geminiKey},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:"user",parts:[{text:JSON.stringify({question,financial_context:payload})}]}],generationConfig:{temperature:.12,maxOutputTokens:850}})}),raw=await response.json().catch(()=>({}));if(!response.ok)return json({error:raw?.error?.message||"Financial Buddy request failed."},502);const answer=raw?.candidates?.[0]?.content?.parts?.find((part:any)=>part.text)?.text||"";if(!answer)return json({error:"Financial Buddy returned an empty response."},502);return json({answer,generated_at:new Date().toISOString(),business:businessR.data?.name||"Selected business"});
}catch(error){console.error("financial-buddy",error);return json({error:error instanceof Error?error.message:"Financial Buddy failed."},500);}});
