import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { authorizeManager,corsHeaders,getAdminClient,googleTokenRefreshError,jsonResponse,maxBatchSize,readJson,RequestError } from "../_shared/rtb.ts";
const GMAIL="https://gmail.googleapis.com/gmail/v1";
function authConfig(){return{accessToken:Deno.env.get("GOOGLE_GMAIL_ACCESS_TOKEN")||Deno.env.get("GOOGLE_ACCESS_TOKEN")||"",refreshToken:Deno.env.get("GOOGLE_GMAIL_REFRESH_TOKEN")||Deno.env.get("GOOGLE_REFRESH_TOKEN")||"",clientId:Deno.env.get("GOOGLE_GMAIL_CLIENT_ID")||Deno.env.get("GOOGLE_CLIENT_ID")||"",clientSecret:Deno.env.get("GOOGLE_GMAIL_CLIENT_SECRET")||Deno.env.get("GOOGLE_CLIENT_SECRET")||""}}
async function token(){const c=authConfig();if(c.accessToken)return c.accessToken;if(!c.clientId||!c.clientSecret||!c.refreshToken)throw new RequestError("Google Gmail sync is not connected.",500);const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:c.refreshToken,grant_type:"refresh_token"})});const p=await r.json().catch(()=>({}));if(!r.ok||!p.access_token)throw googleTokenRefreshError(p,"Payroll Gmail sync","GOOGLE_GMAIL_REFRESH_TOKEN");return p.access_token}
async function gmail(t:string,path:string){const r=await fetch(`${GMAIL}${path}`,{headers:{Authorization:`Bearer ${t}`}});const p=await r.json().catch(()=>({}));if(!r.ok)throw new RequestError(p.error?.message||"Gmail API failed",r.status);return p}
function decode(v=""){try{const p=v.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(v.length/4)*4,"=");return new TextDecoder().decode(Uint8Array.from(atob(p),c=>c.charCodeAt(0)))}catch{return""}}
function text(part:any):string{let out="";if(part?.body?.data)out+=decode(part.body.data)+"\n";for(const p of part?.parts||[])out+=text(p);return out.replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/\s+/g," ").trim()}
function headers(m:any){return Object.fromEntries((m.payload?.headers||[]).map((h:any)=>[String(h.name||"").toLowerCase(),String(h.value||"")]))}
function parse(subject:string,body:string){const s=`${subject} ${body}`;if(!/successfully deposited|has been deposited/i.test(s))return null;if(/you(?:'ve| have) received|funds sent from/i.test(s))return null;const patterns=[/Your\s+\$([\d,]+\.\d{2})\s+transfer to\s+(.+?)\s+has been successfully deposited/i,/Your transfer to\s+(.+?)\s+of\s+\$([\d,]+\.\d{2})\s+has been deposited/i,/transfer to\s+(.+?)\s+was successfully deposited[\s\S]*?\$([\d,]+\.\d{2})/i];for(let i=0;i<patterns.length;i++){const m=s.match(patterns[i]);if(!m)continue;const amount=Number((i===0?m[1]:m[2]).replace(/,/g,""));let name=(i===0?m[2]:m[1]).replace(/\s*\((?:POS\s*PAY|Payroll|Pos Pa)\)\s*/gi," ").trim();if(!name||!Number.isFinite(amount))continue;return{name,amount,key:name.toLowerCase().replace(/[^a-z0-9]/g,"")}}return null}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});try{if(req.method!=="POST")throw new RequestError("POST is required.",405);const admin=getAdminClient();const b=await readJson(req) as any;const businessUnitId=String(b.businessUnitId||b.business_unit_id||"").trim();if(!businessUnitId)throw new RequestError("businessUnitId is required.",400);const worker=Deno.env.get("RTB_SYNC_WORKER_TOKEN")&&req.headers.get("x-rtb-worker-token")===Deno.env.get("RTB_SYNC_WORKER_TOKEN");if(!worker)await authorizeManager(req,admin,businessUnitId,[{module:"finance",minimum:"edit"}]);const t=await token();const max=maxBatchSize(b.maxMessages||b.max_messages,100,250);const q=String(b.query||'newer_than:90d from:(catch@payments.interac.ca OR notify@payments.interac.ca) ("has been deposited" OR "successfully deposited")');const list=await gmail(t,`/users/me/messages?${new URLSearchParams({q,maxResults:String(max),includeSpamTrash:"false"})}`);let inserted=0,matched=0,ignored=0,errors=0;for(const item of list.messages||[]){try{const m=await gmail(t,`/users/me/messages/${encodeURIComponent(item.id)}?format=full`);const h=headers(m);const sender=h.from||"";if(!/@payments\.interac\.ca/i.test(sender)){ignored++;continue}const parsed=parse(h.subject||"",text(m.payload));if(!parsed){ignored++;continue}const depositedAt=m.internalDate?new Date(Number(m.internalDate)).toISOString():null;const {data,error}=await admin.from("finance_payment_confirmations").upsert({business_unit_id:businessUnitId,provider:"interac",source_message_id:String(m.id),source_thread_id:String(m.threadId||""),sender,subject:h.subject||"",recipient_name:parsed.name,recipient_key:parsed.key,amount:parsed.amount,currency:"CAD",deposited_at:depositedAt,payment_status:"deposited",evidence:{source:"gmail",trusted_sender:true}}, {onConflict:"provider,source_message_id"}).select("id").single();if(error)throw error;if(data?.id)inserted++}catch{errors++}}
const {error:matchError}=await admin.rpc("refresh_email_payroll_matches",{p_business_unit_id:businessUnitId});if(matchError){/* private RPC is intentionally unavailable; call via SQL trigger/backfill path when deployed */}
const {count}=await admin.from("finance_payment_confirmations").select("id",{count:"exact",head:true}).eq("business_unit_id",businessUnitId).in("match_status",["suggested","confirmed"]);matched=count||0;return jsonResponse({inserted,matched,ignored,errors,scanned:(list.messages||[]).length})}catch(err){return jsonResponse({error:err.message||"Payroll Gmail sync failed."},err instanceof RequestError?err.status:500)}});
