services:
  wyze-bridge:
    image: mrlt8/wyze-bridge:latest
    container_name: rtb-wyze-bridge
    restart: unless-stopped
    ports:
      - "127.0.0.1:5050:5000"
      - "127.0.0.1:8554:8554"
      - "127.0.0.1:8888:8888"
    env_file:
      - .env
    environment:
      - WB_AUTH=true
      - WB_USERNAME=${WB_USERNAME}
      - WB_PASSWORD=${WB_PASSWORD}
      - WYZE_EMAIL=${WYZE_EMAIL}
      - WYZE_PASSWORD=${WYZE_PASSWORD}
      - API_ID=${WYZE_API_ID}
      - API_KEY=${WYZE_API_KEY}
