create table if not exists public.app_interaction_events (
  id bigint generated by default as identity primary key,
  business_unit_id uuid not null references public.business_units(id) on delete cascade,
  session_id text not null check (char_length(session_id) between 8 and 80),
  event_name text not null check (event_name in ('navigation','repeated_navigation','form_abandoned','client_error')),
  page text not null check (char_length(page) between 1 and 80),
  tab text check (tab is null or char_length(tab) <= 80),
  target text check (target is null or char_length(target) <= 80),
  duration_ms integer check (duration_ms is null or duration_ms between 0 and 86400000),
  metadata jsonb not null default '{}'::jsonb check (
    jsonb_typeof(metadata) = 'object' and pg_column_size(metadata) <= 2048
  ),
  created_at timestamptz not null default now()
);

create index if not exists app_interaction_events_business_created_idx
  on public.app_interaction_events (business_unit_id, created_at desc);
create index if not exists app_interaction_events_event_page_idx
  on public.app_interaction_events (event_name, page, created_at desc);

alter table public.app_interaction_events enable row level security;

revoke all on table public.app_interaction_events from anon, authenticated;
grant insert on table public.app_interaction_events to authenticated;
grant usage, select on sequence public.app_interaction_events_id_seq to authenticated;
grant all on table public.app_interaction_events to service_role;
grant usage, select on sequence public.app_interaction_events_id_seq to service_role;

drop policy if exists "active users can record anonymous app interactions" on public.app_interaction_events;
create policy "active users can record anonymous app interactions"
on public.app_interaction_events
for insert
to authenticated
with check (
  exists (
    select 1
    from public.user_profiles profile
    where profile.id = (select auth.uid())
      and profile.active = true
      and (
        profile.business_unit_id = app_interaction_events.business_unit_id
        or coalesce(profile.permissions->>'business_scope', '') = 'all'
        or coalesce(profile.permissions->'business_unit_ids', '[]'::jsonb)
             ? app_interaction_events.business_unit_id::text
        or coalesce(profile.permissions->'business_unit_ids', '[]'::jsonb)
             ? 'all-businesses'
      )
  )
);

comment on table public.app_interaction_events is
  'Privacy-minimized RTB OS interaction telemetry. Contains no typed content, customer data, payroll values, photos, messages, email, or user id.';
